### ISSUE TITLE
Lang service discovery

### ISSUE THREAD

**Issue by svacina** [cloudhubs/prophet#9]
Create service that will discover the language that was used to code the microservice.

**Comment by i-laird** [comment]
Could the implementation be as simple as looking at file types? Or am I oversimplifying it

**Comment by i-laird** [comment]
The method that GitHub uses to detect project programming languages and is detailed here:
https://github.com/github/linguist

**Comment by svacina** [comment]
Sure, oversimplify, massively.

**Comment by i-laird** [comment]
There is now an endpoint setup in Py Parser for language detection
